// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asmostaidymrcesixebq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbW9zdGFpZHltcmNlc2l4ZWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTQzOTgsImV4cCI6MjA3MTA5MDM5OH0.ZSwTxe4EYm940wg91RegIgqZygzr4jiGrZjyw_C8X1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});